server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: HoneyAI

  datasource:
    url: jdbc:sqlite:./data/honeyai.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
        show_sql: false
    open-in-view: false

  thymeleaf:
    cache: false

honeyai:
  etiquettes:
    siret: "511036780015"
    nom-apiculteur: "ALLEMAND Jean Pierre"
    adresse: "12 chemin des crouzettes Tarreyres 43370 Cussac-sur-Loire"
    telephone: "04.71.03.12.43"
    dluo-duree-jours: 730
    label-width-mm: 60.0
    label-height-mm: 40.0
    labels-per-row: 3
    labels-per-column: 7

logging:
  level:
    root: INFO
    com.honeyai: DEBUG
