spring:
  datasource:
    url: jdbc:sqlite:./data/honeyai.db

  jpa:
    properties:
      hibernate:
        format_sql: false
        show_sql: false

  thymeleaf:
    cache: true

logging:
  level:
    root: INFO
    com.honeyai: INFO
  file:
    name: ./logs/honeyai.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
